services:
  db:
    image: postgres:latest
    container_name: postgres_flowe
    environment:
      POSTGRES_USER: flowe
      POSTGRES_PASSWORD: flowe
      POSTGRES_DB: flowe_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata-integration:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowe -d flowe_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/s1rseul/floweapi:${BACKEND_TAG:-latest}
    container_name: flowe-api-integration
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/flowe_dev
      SPRING_DATASOURCE_USERNAME: flowe
      SPRING_DATASOURCE_PASSWORD: flowe
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata-integration: